### ISSUE TITLE
any tips on this?

### ISSUE THREAD

**Issue by liamxg** [lauringlab/sapphire_covid_display#1]
<img width="1048" alt="image" src="https://github.com/lauringlab/sapphire_covid_display/assets/46078579/2751f907-8a8c-498a-886e-21bf11ccd19e">

**Comment by liamxg** [comment]
thanks.

**Comment by liamxg** [comment]
@julesjulesjules

**Comment by julesjulesjules** [comment]
(1) Is tidyverse installed?
(2) Is the variable COUNTY present in the covid_cases_county dataframe? (that dataframe should be filled with cases_deaths_by_county_state_of_michigan_20220420.csv data (or the most current data file name you have) that was downloaded from the State of Michigan website [Cases and Deaths by County by Date 
of Onset of Symptoms and Date of Death from https://www.michigan.gov/coronavirus/stats])

**Comment by liamxg** [comment]
@julesjulesjules thanks, I just re-download the repository, and run it, now it is okay. great app.
